name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-sdk/platform-tools:${{ env.PATH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip \
            build-essential libffi-dev zlib1g-dev libncurses6 libssl-dev \
            git ant wget

      - name: Install Buildozer & p4a
        run: |
          pip install --upgrade pip
          pip install cython==0.29.36
          pip install buildozer

      - name: Download Android SDK command-line tools
        run: |
          mkdir -p "$ANDROID_HOME/cmdline-tools"
          cd "$ANDROID_HOME/cmdline-tools"
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-9477386_latest.zip
          rm commandlinetools-linux-9477386_latest.zip
          mv cmdline-tools latest

      - name: Accept licenses & install SDK/NDK
        run: |
          yes | sdkmanager --sdk_root="$ANDROID_HOME" --licenses
          sdkmanager --sdk_root="$ANDROID_HOME" \
            "platform-tools" "platforms;android-33" "build-tools;33.0.0" \
            "ndk;25.2.9519653"

      - name: Clean Buildozer cache
        run: |
          rm -rf .buildozer bin

      - name: Prepare buildozer.spec
        run: |
          # Ensure required config set
          grep -q '^log_level *= *2' buildozer.spec || echo "log_level = 2" >> buildozer.spec
          grep -q '^android.sdk_path' buildozer.spec || echo "android.sdk_path = $ANDROID_HOME" >> buildozer.spec
          grep -q '^android.ndk_path' buildozer.spec || echo "android.ndk_path = $ANDROID_HOME/ndk/25.2.9519653" >> buildozer.spec

      - name: Build APK and capture logs
        run: |
          mkdir -p "$ANDROID_HOME/tools/bin"
          ln -sf "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" "$ANDROID_HOME/tools/bin/sdkmanager" || true

          buildozer android clean && buildozer android debug 2>&1 | tee buildozer_build_output.log
        continue-on-error: true

      - name: Show log tail
        run: |
          echo "=== Last 50 lines of build log ==="
          tail -n 50 buildozer_build_output.log || echo "<no log file found>"

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: buildozer-log
          path: buildozer_build_output.log

      - name: Upload APK (if built)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: bin/*.apk
